### ISSUE TITLE
Flask Release Checklist

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-monorepo#770]
Make an internal Flask release checklist. Something like:

```
- [ ] Announce on discussions
- [ ] Announce on Tweeter MMDev
- [ ] Check that cli template still works
- [ ] Check repo (A), (B), (C) for breaking changes
- [ ] Check repo (A), (B), (C) using latest release
```

We’ll hopefully automate much of it as time goes on, but for now a checklist will be very helpful. This template will be on Notion!

**Comment by Montoya** [comment]
OK here's a proposed list, feedback please: https://www.notion.so/Flask-Release-Checklist-21abeb46f92243c7a189fb511caa7ed2

**Comment by rekmarks** [comment]
The Notion list is good; let's ship and maintain that.
